# Generated by Django 6.0.7 on 2026-07-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پرسشنامه')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='هزینه')),
                ('question', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد سوالات')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('question_type', models.CharField(choices=[('MC', 'چندگزینه\u200cای'), ('TX', 'متن آزاد'), ('SC', 'مقیاس (مثل لیکرت)')], max_length=2, verbose_name='نوع سؤال')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('required', models.BooleanField(default=True, verbose_name='اجباری')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.attribute')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionnaire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن گزینه')),
                ('value', models.IntegerField(default=0, verbose_name='ارزش عددی (برای امتیازدهی)')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.questionnaire')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ\u200cدهنده')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='پاسخ متنی')),
                ('scale_value', models.IntegerField(blank=True, null=True, verbose_name='ارزش مقیاس')),
                ('RT', models.PositiveIntegerField(blank=True, null=True, verbose_name='زمان پاسخ\u200cدهی (ثانیه)')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.response')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_questions', models.IntegerField(default=0, verbose_name='تعداد سوالات مربوط به ویژگی')),
                ('raw_score', models.FloatField(default=0.0, verbose_name='نمره خام')),
                ('average_score', models.FloatField(default=0.0, verbose_name='میانگین نمره')),
                ('sum_rt', models.PositiveIntegerField(default=0, verbose_name='جمع RT')),
                ('average_rt', models.FloatField(default=0.0, verbose_name='میانگین RT')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.attribute', verbose_name='Attribute')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionnaire', verbose_name='آزمون')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.response', verbose_name='Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('response', 'attribute'), name='unique_response_attribute')],
                'unique_together': {('response', 'attribute')},
            },
        ),
    ]
