# Generated by Django 6.0.7 on 2026-07-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_fa', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='SessionType/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'SessionType',
                'verbose_name_plural': 'SessionType',
            },
        ),
        migrations.CreateModel(
            name='PsychologistNewPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepting_new_patients', models.BooleanField(default=False, verbose_name='مراجع جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_patients', to='accounts.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('session_duration', models.PositiveIntegerField(default=45, verbose_name='مدت جلسه (دقیقه)')),
                ('break_duration', models.PositiveIntegerField(default=15, verbose_name='استراحت بین جلسات (دقیقه)')),
                ('price', models.PositiveIntegerField(verbose_name='هزینه جلسه')),
                ('booking_days_ahead', models.PositiveIntegerField(default=30, verbose_name='نمایش نوبت تا چند روز آینده')),
                ('minimum_booking_hours', models.PositiveIntegerField(default=2, verbose_name='حداقل زمان رزرو قبل از جلسه (ساعت)')),
                ('cancel_before_hours', models.PositiveIntegerField(default=24, verbose_name='مهلت لغو نوبت (ساعت)')),
                ('require_confirmation', models.BooleanField(default=False, verbose_name='نیاز به تأیید رزرو')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='اعتبار از تاریخ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='اعتبار تا تاریخ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='work_schedules', to='accounts.role', verbose_name='نقش\u200cهای مجاز')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='accounts.psychologist', verbose_name='متخصص')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_schedules', to='appointment.room', verbose_name='اتاق')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='appointment.sessiontype')),
            ],
            options={
                'verbose_name': 'WorkSchedule',
                'verbose_name_plural': 'WorkSchedule',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('session_duration', models.PositiveIntegerField()),
                ('end_time', models.TimeField()),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('done', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.psychologist')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointment.room')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment.sessiontype')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointment.workschedule')),
            ],
        ),
    ]
