# Generated by Django 6.0.7 on 2026-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_room_is_active_room_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
