# Generated by Django 6.0.7 on 2026-07-11 21:34

import ckeditor_uploader.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'Fields of Study',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='پیشوند آدرس')),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='platform/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platform',
            },
        ),
        migrations.CreateModel(
            name='PsychologistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نوع متخصص')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='psychologist_types/icons/', verbose_name='آیکون')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='psychologist_types/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'Section Type',
                'verbose_name_plural': 'Section Type Accounts',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='Specialty/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'تخصص ها',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='accounts.city')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='نقش\u200cها')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='accounts.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province'),
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/psychologists/profiles', verbose_name='عکس پروفایل')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to=settings.AUTH_USER_MODEL)),
                ('PsychologistType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsychologistType', to='accounts.psychologisttype')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'Psychologists',
            },
        ),
        migrations.CreateModel(
            name='PsychologistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('membership_card', 'عضویت'), ('license_card', 'پروانه اشتغال'), ('certificate', 'گواهینامه'), ('other', 'سایر')], max_length=50, verbose_name='نوع سند')),
                ('document_image', models.ImageField(upload_to='images/psychologists/documents/', verbose_name='تصویر سند')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('code', models.CharField(blank=True, max_length=200, verbose_name='کد')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media', to='accounts.platform')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='accounts.psychologist')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/Secretary/profiles', verbose_name='عکس پروفایل')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='رنگ زمینه')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='رنگ متن')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.psychologist')),
                ('section_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='accounts.sectiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='accounts.fieldofstudy')),
            ],
            options={
                'verbose_name': 'گرایش تحصیلی',
                'verbose_name_plural': 'Specializations',
                'unique_together': {('name', 'field')},
            },
        ),
        migrations.CreateModel(
            name='PsychologistSpecialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='accounts.psychologist')),
                ('specialties', models.ManyToManyField(blank=True, related_name='psychologists', to='accounts.specialty', verbose_name='زمینه کاری')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='University/icons/', verbose_name='آیکون')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='accounts.city')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='PsychologistDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Associate', 'کاردانی'), ('Bachelor', 'کارشناسی'), ('Master', 'کارشناسی ارشد'), ('PhD', 'دکتری'), ('PostDoc', 'پسادکتری')], max_length=9)),
                ('start_year', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تحصیل')),
                ('graduation_year', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تحصیل')),
                ('study_status', models.CharField(choices=[('Studying', 'در حال تحصیل'), ('Graduated', 'فارغ\u200cالتحصیل'), ('Dropped', 'انصراف داده')], default='graduated', max_length=20, verbose_name='وضعیت تحصیل')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان پایان\u200cنامه')),
                ('degree_file', models.FileField(blank=True, null=True, upload_to='degrees/', verbose_name='فایل مدرک')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('display_config', models.JSONField(blank=True, default=dict)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='accounts.psychologist')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='accounts.specialization')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='accounts.university')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
    ]
