# Generated by Django 5.2.7 on 2026-06-27 13:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'Fields of Study',
            },
        ),
        migrations.CreateModel(
            name='PsychologistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نوع متخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='psychologist_types/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'نوع متخصص',
                'verbose_name_plural': 'انواع متخصصان',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تخصص ها',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission', verbose_name='user permissions')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='accounts.city')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='نقش\u200cها')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='accounts.country')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='accounts.province'),
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/psychologists/profiles', verbose_name='عکس پروفایل')),
                ('banner_image', models.ImageField(blank=True, help_text='تصویر هدر یا تبلیغاتی (مثلاً 1200x400)', null=True, upload_to='static/images/psychologists/banners', verbose_name='بنر تبلیغاتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist', to=settings.AUTH_USER_MODEL)),
                ('PsychologistType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsychologistType', to='accounts.psychologisttype')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'Psychologists',
            },
        ),
        migrations.CreateModel(
            name='PsychologistNewPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepting_new_patients', models.BooleanField(default=True, verbose_name='مراجع جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_patients', to='accounts.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('bio', 'Biography'), ('books', 'Books & Publications'), ('awards', 'Awards & Honors'), ('associations', 'Associations & Memberships'), ('experience', 'Work Experience'), ('approaches', 'Therapeutic Approaches'), ('disorders', 'Disorders Treated'), ('education', 'Education'), ('certifications', 'Certifications'), ('research', 'Research Activities'), ('custom', 'Custom Section')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.psychologist')),
            ],
            options={
                'verbose_name': 'بخش متخصص',
                'verbose_name_plural': 'بخش\u200cهای متخصص',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PsychologistSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TW', 'Twitter/X'), ('LI', 'LinkedIn'), ('IG', 'Instagram'), ('FB', 'Facebook'), ('OT', 'Other')], max_length=2)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='accounts.psychologist')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/psychologists/profiles', verbose_name='عکس پروفایل')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منشی',
                'verbose_name_plural': 'منشی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='accounts.fieldofstudy')),
            ],
            options={
                'verbose_name': 'گرایش تحصیلی',
                'verbose_name_plural': 'Specializations',
                'unique_together': {('name', 'field')},
            },
        ),
        migrations.CreateModel(
            name='PsychologistSpecialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='accounts.psychologist')),
                ('specialties', models.ManyToManyField(blank=True, related_name='psychologists', to='accounts.specialty', verbose_name='زمینه کاری')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='accounts.city')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='PsychologistDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Associate', 'کاردانی'), ('Bachelor', 'کارشناسی'), ('Master', 'کارشناسی ارشد'), ('PhD', 'دکتری'), ('PostDoc', 'پسادکتری')], max_length=9)),
                ('start_year', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع تحصیل')),
                ('graduation_year', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تحصیل')),
                ('study_status', models.CharField(choices=[('Studying', 'در حال تحصیل'), ('Graduated', 'فارغ\u200cالتحصیل'), ('Dropped', 'انصراف داده')], default='graduated', max_length=20, verbose_name='وضعیت تحصیل')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل')),
                ('thesis_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان پایان\u200cنامه')),
                ('degree_file', models.FileField(blank=True, null=True, upload_to='degrees/', verbose_name='فایل مدرک')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='accounts.fieldofstudy')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='accounts.psychologist')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='accounts.specialization')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='accounts.university')),
            ],
            options={
                'verbose_name': 'مدرک دانشگاهی',
                'verbose_name_plural': 'مدارک دانشگاهی',
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
    ]
