# Generated by Django 6.0.7 on 2026-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
