# Generated by Django 5.2.7 on 2026-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='psychologistdegree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='psychologisttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secretary',
            options={},
        ),
        migrations.AddField(
            model_name='psychologist',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعالیت'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعالیت'),
        ),
    ]
