# Generated by Django 6.0.7 on 2026-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistspecialties',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعالیت'),
        ),
        migrations.AddField(
            model_name='psychologistspecialties',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
    ]
