# Generated by Django 5.2.7 on 2026-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistdegree',
            name='visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
