# Generated by Django 5.2.7 on 2025-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_country_fieldofstudy_specialty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'گرایش تحصیلی', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AddField(
            model_name='psychologist',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='تصویر هدر یا تبلیغاتی (مثلاً 1200x400)', null=True, upload_to='static/images/psychologists/banners', verbose_name='بنر تبلیغاتی'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='عکس پرسنلی یا حرفه\u200cای (مثلاً 400x400)', null=True, upload_to='static/images/psychologists/profiles', verbose_name='عکس پروفایل'),
        ),
    ]
