# Generated by Django 6.0.7 on 2026-07-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_country_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='accounts.country'),
        ),
    ]
