# Generated by Django 6.0.7 on 2026-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_psychologistspecialties_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('basic', 'پایه'), ('readonly', 'فقط خواندنی'), ('editor', 'ویرایشگر'), ('advanced', 'پیشرفته')], default='basic', max_length=20, verbose_name='سطح دسترسی کلی'),
        ),
    ]
