# Generated by Django 5.2.7 on 2026-07-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_access_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PsychologistSpecialties',
            new_name='PsychologistSpecialtie',
        ),
    ]
