# Generated by Django 5.2.7 on 2025-12-03 10:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام نوع متخصص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.ImageField(blank=True, help_text='آیکون کوچک برای نمایش در فیلترها (مثلاً 64x64)', null=True, upload_to='psychologist_types/icons/', verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'نوع متخصص',
                'verbose_name_plural': 'انواع متخصصان',
            },
        ),
        migrations.AddField(
            model_name='psychologist',
            name='associations',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='مثلاً عضو نظام روانشناسی، انجمن روانشناسی ایران، APA، ISST و ...', verbose_name='عضویت در انجمن\u200cها و سازمان\u200cها'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='authored_books',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='لیست کتاب\u200cها، سال انتشار، ناشر و توضیح کوتاه (می\u200cتوانید از لیست یا جدول استفاده کنید)', verbose_name='تألیفات و کتاب\u200cها'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='awards',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='جوایز علمی، رتبه\u200cهای جشنواره\u200cها، تقدیرنامه\u200cها و ...', verbose_name='جوایز و افتخارات'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='disorders_treated',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='اضطراب، افسردگی، وسواس، اختلالات شخصیت، مشاوره زوج، کودک و نوجوان و ...', verbose_name='اختلالات و حوزه\u200cهای '),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='therapeutic_approaches',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='مثلاً CBT، طرحواره\u200cدرمانی، ACT، روان\u200cتحلیلگری، ذهن\u200cآگاهی، EMDR و ...', verbose_name='رویکردهای درمانی'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='work_experience',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='کلینیک\u200cها، بیمارستان\u200cها، مراکز مشاوره قبلی به همراه سال\u200cها', verbose_name='سوابق کاری و حرفه\u200cای'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Availability details, e.g., days and hours of consultation', null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='PsychologistType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsychologistType', to='accounts.psychologisttype'),
        ),
    ]
