# Generated by Django 5.2.7 on 2026-07-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_psychologistdegree_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistdegree',
            name='graduation_year',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان تحصیل'),
        ),
        migrations.AlterField(
            model_name='psychologistdegree',
            name='start_year',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع تحصیل'),
        ),
    ]
