# Generated by Django 5.2.7 on 2026-07-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_psychologistdegree_graduation_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologistdegree',
            name='visibility',
        ),
        migrations.AddField(
            model_name='psychologistdegree',
            name='gpa_active',
            field=models.BooleanField(default=False, verbose_name='نمایش معدل'),
        ),
        migrations.AddField(
            model_name='psychologistdegree',
            name='specialization_active',
            field=models.BooleanField(default=False, verbose_name='نمایش رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='psychologistdegree',
            name='thesis_active',
            field=models.BooleanField(default=False, verbose_name='نمایش پایان\u200cنامه'),
        ),
        migrations.AddField(
            model_name='psychologistdegree',
            name='university_active',
            field=models.BooleanField(default=False, verbose_name='نمایش دانشگاه محل تحصیل '),
        ),
        migrations.AddField(
            model_name='psychologistdegree',
            name='year_active',
            field=models.BooleanField(default=False, verbose_name='نمایش سال تحصیل '),
        ),
    ]
