# Generated by Django 5.2.7 on 2025-12-03 10:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_psychologisttype_psychologist_associations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='associations',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='مثلاً عضو نظام روانشناسی، انجمن روانشناسی ایران، APA، ISST و ...', null=True, verbose_name='عضویت در انجمن\u200cها و سازمان\u200cها'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='authored_books',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='لیست کتاب\u200cها، سال انتشار، ناشر و توضیح کوتاه (می\u200cتوانید از لیست یا جدول استفاده کنید)', null=True, verbose_name='تألیفات و کتاب\u200cها'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='awards',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='جوایز علمی، رتبه\u200cهای جشنواره\u200cها، تقدیرنامه\u200cها و ...', null=True, verbose_name='جوایز و افتخارات'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='disorders_treated',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='اضطراب، افسردگی، وسواس، اختلالات شخصیت، مشاوره زوج، کودک و نوجوان و ...', null=True, verbose_name='اختلالات و حوزه\u200cهای '),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='therapeutic_approaches',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='مثلاً CBT، طرحواره\u200cدرمانی، ACT، روان\u200cتحلیلگری، ذهن\u200cآگاهی، EMDR و ...', null=True, verbose_name='رویکردهای درمانی'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='work_experience',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='کلینیک\u200cها، بیمارستان\u200cها، مراکز مشاوره قبلی به همراه سال\u200cها', null=True, verbose_name='سوابق کاری و حرفه\u200cای'),
        ),
    ]
