# Generated by Django 6.0.7 on 2026-07-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_psychologistspecialties_psychologistspecialtie'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='رنگ زمینه'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='رنگ متن'),
        ),
    ]
