# Generated by Django 5.2.7 on 2026-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_psychologistdegree_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistdegree',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
