# Generated by Django 5.2.7 on 2026-07-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_psychologistdegree_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='license_code',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='membership_code',
        ),
        migrations.CreateModel(
            name='PsychologistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('membership_card', 'عضویت'), ('license_card', 'پروانه اشتغال'), ('certificate', 'گواهینامه'), ('other', 'سایر')], max_length=50, verbose_name='نوع سند')),
                ('image', models.ImageField(upload_to='documents/psychologists/', verbose_name='تصویر سند')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('code', models.CharField(blank=True, max_length=200, verbose_name='کد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.psychologist')),
            ],
            options={
                'verbose_name': 'سند متخصص',
                'verbose_name_plural': 'اسناد متخصصان',
                'ordering': ['document_type'],
                'unique_together': {('psychologist', 'document_type')},
            },
        ),
    ]
