# Generated by Django 5.2.7 on 2026-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_psychologist_license_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologistdocument',
            name='image',
            field=models.ImageField(upload_to='images/psychologists/documents/', verbose_name='تصویر سند'),
        ),
    ]
