# Generated by Django 6.0.7 on 2026-07-10 21:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_psychologistdocument_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='psychologistdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='psychologistdocument',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت فعالیت'),
        ),
        migrations.AddField(
            model_name='psychologistdocument',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده'),
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistdocument',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psychologisttype',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='psychologistdocument',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='psychologistdocument',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='psychologistdocument',
            name='verified_at',
        ),
    ]
