# Generated by Django 6.0.7 on 2026-07-10 23:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_psychologistdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologistdocument',
            options={},
        ),
        migrations.RemoveField(
            model_name='psychologistsection',
            name='content',
        ),
        migrations.AddField(
            model_name='psychologistsection',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
