# Generated by Django 6.0.7 on 2026-07-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_psychologistdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psychologistsection',
            options={},
        ),
        migrations.AlterField(
            model_name='psychologistsection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='psychologistsection',
            name='section_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='accounts.sectiontype'),
        ),
    ]
